### ISSUE TITLE
Not getting exact number of results

### ISSUE THREAD

**Issue by Nisthar** [gsouf/google-url#27] opened 2016-01-18 15:31 UTC
I am not getting exact number of results that i am requesting for. I think its because of occassional image results in the results. How can i filter this and get exact number of results?

**Comment by gsouf** [comment] 2016-01-18 16:04
@Nisthar That's possible, some results types are not implemented in the version 1 of the library. Can you give me more details about your search then I can see what is going wrong exatcly.

In addition the library is going to have a huge refactoring, for end january / early february, You have to know that the support for this version wont be maintained for a long time.

**Comment by Nisthar** [comment] 2016-01-18 16:16
@gsouf You can search for the keyword "reviewill" in google and see there are images in the result which is not scraped by the library. So it will return one less than the total result(in this case i searched for 15 results. got only 14 results).

**Comment by Nisthar** [comment] 2016-01-18 16:31
@gsouf Btw I am getting captcha error recently. Why this happend? and how can i manually solve it?

**Comment by gsouf** [comment] 2016-01-18 17:04
Can you give me the exact url of the search (``echo $googleUrl->getUrl();``)? Because the serp will change according to some parameters, e.g:  the local parameters or the tld. That means with my current search param I'm not able to reproduce the issue.

About captcha there is no way to solve it from the library currently. This happens because you submited too many requests in a short time and google detected you are spamming it.

**Comment by Nisthar** [comment] 2016-01-18 17:17
I can't get the exact url as google blocked me.

Btw can i use proxy to bypass the captcha temporarily? Will it work?

**Comment by gsouf** [comment] 2016-01-18 17:26
It will work. 

You can get the url at anytime, just do  it before searching results

**Comment by Nisthar** [comment] 2016-01-18 17:27
Ok. Url is https://www.google.com/search?q=reviewill&start=0&num=15&complete=0&pws=0&hl=en&lr=lang_en

**Comment by Nisthar** [comment] 2016-01-18 17:47
Btw will using proxy bypass the captcha?

**Comment by Nisthar** [comment] 2016-01-19 06:09
@gsouf I am trying to get news result from google.
My code:
     $googleUrl=new \GoogleUrl();
     $googleUrl->setParam("tbm", "nws");
     $googleUrl->setNumberResults($numberofsearch);
   
    try{
    $simpsonPage=$googleUrl->setPage(0)->search($serachString,$proxy = null);
    $positions=$simpsonPage->getPositions();
    }catch(\GoogleUrl\Exception\CaptachaException $e){
    die("Please complete the captcha to proceed to the search result");
    }
    But i think its not returning the results.

**Comment by gsouf** [comment] 2016-01-19 09:12
For your first problem it's either the video result or the image results that are not parsed, not sure.

For your second problem news results are not parsed, that's planed for the next release. 

that wont be fixed in the current version for the moment. I leave it open then I can remember that's not fixed

PS: Please remember about opening 1 issue per problem and try to dont mixup differents topics in the same issue

**Comment by Nisthar** [comment] 2016-01-19 10:18
@gsouf I was going to create new issue. But thought these are not really a issue.
Anyway i think its easy to scrape news,image and video results, I managed to implement it in my project.

**Comment by gsouf** [comment] 2016-03-30 12:52
I'm closing the issue because it's now available in https://github.com/serp-spider/search-engine-google

**Closed by gsouf** 2016-03-30 12:52 UTC
